## Non-Majors Survey Results

Jismi Mathew

10/08/2025

Purpose: Explore Non-Majors Survey dataset using Python, and perform data cleaning using pandas.

In [1]:
import pandas as pd

In [2]:
datafile = 'Non-Majors_Survey_Results-Fall 2024.csv'
df = pd.read_csv(datafile, parse_dates=True)

Explore Data:

In [3]:
df.describe()

       On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?
count                                          92.000000
mean                                            2.576087
std                                             1.131310
min                                             1.000000
25%                                             2.000000
50%                                             3.000000
75%                                             3.000000
max                                             5.000000

In [4]:
df.columns

Index(['Timestamp', 'Which course are you currently enrolled in?',
       'What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]',
       'What motivated you to seek a computing class at CCM? [To keep current in computing skills]',
       'What motivated you to seek a computing class at CCM? [Career Advancement]',
       'What motivated you to seek a computing class at CCM? [Career Change]',
       'What motivated you to seek a computing class at CCM? [Professional Development]',
       'What motivated you to seek a computing class at CCM? [Job Displacement]',
       'What motivated you to seek a computing class at CCM? [Relocation]',
       'What motivated you to seek a computing class at CCM? [IT Industry Certifications]',
       'What motivated you to seek a computing class at CCM? [Financial]',
       'What motivated you to seek a computing class at CCM? [Personal Enrichment]',
       'What motivated you to seek a computing class at CCM? [Curiosity]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]',
       'How did you hear about County College of Morris  [CCM Web site]',
       'How did you hear about County College of Morris  [Billboard]',
       'How did you hear about County College of Morris  [Television]',
       'How did you hear about County College of Morris  [Radio]',
       'How did you hear about County College of Morris  [Social Media]',
       'How did you hear about County College of Morris  [Community Event]',
       'How did you hear about County College of Morris  [Family member or friend]',
       'How did you hear about County College of Morris  [Employer]',
       'How did you hear about County College of Morris  [Current student]',
       'How did you hear about County College of Morris  [Alumni]',
       'How did you hear about County College of Morris  [High School]',
       'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]',
       'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]',
       'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]',
       'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]',
       'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]',
       'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]',
       'To what extent did the following impact your decision to attend County College of Morris? [College reputation]',
       'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]',
       'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]',
       'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]',
       'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]',
       'What degree program are you currently enrolled in?',
       'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]',
       'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]',
       'Did you receive information about our computing course from any of the following sources? [CCM Admissions]',
       'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]',
       'Did you receive information about our computing course from any of the following sources? [Employer]',
       'Did you receive information about our computing course from any of the following sources? [Other]',
       'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]',
       'Gender', 'Race/ethnicity', 'Age '],
      dtype='object')

In [5]:
df.shape

(92, 71)

In [6]:
df.dtypes

Timestamp                                                                                                                                    object
Which course are you currently enrolled in?                                                                                                  object
What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]                                      object
What motivated you to seek a computing class at CCM? [To keep current in computing skills]                                                   object
What motivated you to seek a computing class at CCM? [Career Advancement]                                                                    object
                                                                                                                                              ...
If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]                       object
If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]    object
Gender                                                                                                                                       object
Race/ethnicity                                                                                                                               object
Age                                                                                                                                          object
Length: 71, dtype: object

In [7]:
df.head(5)

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

In [8]:
df.tail

<bound method NDFrame.tail of                      Timestamp   Which course are you currently enrolled in?  \
0   2024/09/10 10:47:35 AM AST  CMP 126 Computer Technology and Applications
1   2024/09/10 11:00:05 AM AST  CMP 126 Computer Technology and Applications
2   2024/09/10 11:02:51 AM AST  CMP 126 Computer Technology and Applications
3   2024/09/10 11:05:25 AM AST  CMP 126 Computer Technology and Applications
4    2024/09/10 8:37:36 PM AST         CMP 101 Computer Information Literacy
..                         ...                                           ...
87  2024/09/20 10:55:34 PM AST         CMP 101 Computer Information Literacy
88  2024/09/20 11:02:45 PM AST  CMP 126 Computer Technology and Applications
89  2024/09/20 11:07:16 PM AST  CMP 126 Computer Technology and Applications
90   2024/09/21 5:06:23 PM AST         CMP 101 Computer Information Literacy
91  2024/09/22 10:08:19 PM AST  CMP 126 Computer Technology and Applications

   What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                Yes
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [To keep current in computing skills]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                 Yes
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                Yes
91                                                Yes

   What motivated you to seek a computing class at CCM? [Career Advancement]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [Career Change]  \
0                                                 Yes
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [Professional Development]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                 No
88                                                Yes
89                                                Yes
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [Job Displacement]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [Relocation]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [IT Industry Certifications]  \
0                                                  No
1                                                  No
2                                                  No
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

    ...  \
0   ...
1   ...
2   ...
3   ...
4   ...
..  ...
87  ...
88  ...
89  ...
90  ...
91  ...

   If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]  \
0                                                 Yes
1                                                 Yes
2                                                  No
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]  \
0                                                  No
1                                                 Yes
2                                                  No
3                                                 Yes
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                Yes
90                                                 No
91                                                Yes

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                 Yes
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                Yes
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                Yes

               Gender                                     Race/ethnicity  \
0   Prefer not to say  Hispanic or Latino;Black/African American;Whit...
1               Woman                                 Hispanic or Latino
2                 Man                                Choose not to reply
3                 Man                                 Hispanic or Latino
4               Woman                                    White/Caucasian
..                ...                                                ...
87              Woman                 Hispanic or Latino;White/Caucasian
88              Woman                                 Hispanic or Latino
89              Woman                             Black/African American
90                Man                                 Hispanic or Latino
91              Woman                                              Asian

              Age
0            19-20
1            19-20
2   18 and younger
3            19-20
4            19-20
..             ...
87           21-24
88           19-20
89           19-20
90           19-20
91           21-24

[92 rows x 71 columns]>

In [9]:
df.sample()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20

In [10]:
df.info

<bound method DataFrame.info of                      Timestamp   Which course are you currently enrolled in?  \
0   2024/09/10 10:47:35 AM AST  CMP 126 Computer Technology and Applications
1   2024/09/10 11:00:05 AM AST  CMP 126 Computer Technology and Applications
2   2024/09/10 11:02:51 AM AST  CMP 126 Computer Technology and Applications
3   2024/09/10 11:05:25 AM AST  CMP 126 Computer Technology and Applications
4    2024/09/10 8:37:36 PM AST         CMP 101 Computer Information Literacy
..                         ...                                           ...
87  2024/09/20 10:55:34 PM AST         CMP 101 Computer Information Literacy
88  2024/09/20 11:02:45 PM AST  CMP 126 Computer Technology and Applications
89  2024/09/20 11:07:16 PM AST  CMP 126 Computer Technology and Applications
90   2024/09/21 5:06:23 PM AST         CMP 101 Computer Information Literacy
91  2024/09/22 10:08:19 PM AST  CMP 126 Computer Technology and Applications

   What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                Yes
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [To keep current in computing skills]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                 Yes
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                Yes
91                                                Yes

   What motivated you to seek a computing class at CCM? [Career Advancement]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [Career Change]  \
0                                                 Yes
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [Professional Development]  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                 Yes
..                                                ...
87                                                 No
88                                                Yes
89                                                Yes
90                                                 No
91                                                Yes

   What motivated you to seek a computing class at CCM? [Job Displacement]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [Relocation]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   What motivated you to seek a computing class at CCM? [IT Industry Certifications]  \
0                                                  No
1                                                  No
2                                                  No
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

    ...  \
0   ...
1   ...
2   ...
3   ...
4   ...
..  ...
87  ...
88  ...
89  ...
90  ...
91  ...

   If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]  \
0                                                 Yes
1                                                 Yes
2                                                  No
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                Yes
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]  \
0                                                  No
1                                                 Yes
2                                                  No
3                                                 Yes
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                Yes
90                                                 No
91                                                Yes

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]  \
0                                                  No
1                                                 Yes
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                 No
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                 Yes
4                                                  No
..                                                ...
87                                                Yes
88                                                 No
89                                                Yes
90                                                 No
91                                                 No

   If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]  \
0                                                  No
1                                                  No
2                                                 Yes
3                                                  No
4                                                  No
..                                                ...
87                                                 No
88                                                 No
89                                                 No
90                                                 No
91                                                Yes

               Gender                                     Race/ethnicity  \
0   Prefer not to say  Hispanic or Latino;Black/African American;Whit...
1               Woman                                 Hispanic or Latino
2                 Man                                Choose not to reply
3                 Man                                 Hispanic or Latino
4               Woman                                    White/Caucasian
..                ...                                                ...
87              Woman                 Hispanic or Latino;White/Caucasian
88              Woman                                 Hispanic or Latino
89              Woman                             Black/African American
90                Man                                 Hispanic or Latino
91              Woman                                              Asian

              Age
0            19-20
1            19-20
2   18 and younger
3            19-20
4            19-20
..             ...
87           21-24
88           19-20
89           19-20
90           19-20
91           21-24

[92 rows x 71 columns]>

Clean Data:

Show Data before changes:

In [11]:
df.head()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

In [12]:
# make all column names lowercase and replace spaces and punctuation with underscores
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
      .str.replace("’", "", regex=False)
      .str.replace("'", "", regex=False)
      .str.replace("?", "", regex=False)
      .str.replace("&", "and", regex=False)
      .str.replace("/", "_", regex=False)
      .str.replace(",", "", regex=False)
      .str.replace("[", "", regex=False)
      .str.replace("]", "", regex=False)
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
      .str.replace("__", "_", regex=False)
      .str.strip("_")
)

In [13]:
df.head()

,timestamp,which_course_are_you_currently_enrolled_in,what_motivated_you_to_seek_a_computing_class_at_ccm_its_a_required_class_for_the_degree_im_seeking,what_motivated_you_to_seek_a_computing_class_at_ccm_to_keep_current_in_computing_skills,what_motivated_you_to_seek_a_computing_class_at_ccm_career_advancement,what_motivated_you_to_seek_a_computing_class_at_ccm_career_change,what_motivated_you_to_seek_a_computing_class_at_ccm_professional_development,what_motivated_you_to_seek_a_computing_class_at_ccm_job_displacement,what_motivated_you_to_seek_a_computing_class_at_ccm_relocation,what_motivated_you_to_seek_a_computing_class_at_ccm_it_industry_certifications,...,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_cybersecurity,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_app_development,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_data_analytics,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_machine_learning_artificial_intelligence,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_computer_programming,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_game_design,if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_hardware_installation_and_repair,gender,race_ethnicity,age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

In [14]:
# rename the useful columns to shorter names
df.rename(columns={
    # Basic
    "which_course_are_you_currently_enrolled_in": "course",
    "on_a_scale_of_1_to_5_with_1_being_not_at_all_interested_and_5_being_extremely_interested_how_interested_are_you_taking_more_courses_in_computer_science_information_technology_or_game_development?": "interest",
    "race_ethnicity": "race",

    # Motivation questions
    "what_motivated_you_to_seek_a_computing_class_at_ccm_its_a_required_class_for_the_degree_im_seeking": "motivation_required_course",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_to_keep_current_in_computing_skills": "motivation_keep_current",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_career_advancement": "motivation_career_advancement",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_career_change": "motivation_career_change",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_professional_development": "motivation_prof_dev",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_job_displacement": "motivation_job_displacement",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_relocation": "motivation_relocation",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_it_industry_certifications": "motivation_it_certifications",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_financial": "motivation_financial",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_personal_enrichment": "motivation_enrichment",
    "what_motivated_you_to_seek_a_computing_class_at_ccm_curiosity": "motivation_curiosity",

    # Interest (future courses)
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_web_development": "interest_web_development",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_cybersecurity": "interest_cybersecurity",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_app_development": "interest_app_development",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_data_analytics": "interest_data_analytics",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_machine_learning_artificial_intelligence": "interest_ml_ai",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_computer_programming": "interest_programming",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_game_design": "interest_game_design",
    "if_you_answered_that_you_were_interested_in_taking_more_computing_classes_which_ones_interest_you_most_hardware_installation_and_repair": "interest_hardware_repair"
}, inplace=True)

Show data after column names changed

In [15]:
df.head()

,timestamp,course,motivation_required_course,motivation_keep_current,motivation_career_advancement,motivation_career_change,motivation_prof_dev,motivation_job_displacement,motivation_relocation,motivation_it_certifications,...,interest_cybersecurity,interest_app_development,interest_data_analytics,interest_ml_ai,interest_programming,interest_game_design,interest_hardware_repair,gender,race,age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20

Check if any duplicate rows:

In [16]:
df.duplicated().sum()

0

No duplicates in this dataset

In [17]:
# clean text data
text_columns = ['course', 'gender', 'race', 'age']
for col in text_columns:
    if col in df.columns:
        df[col] = (df[col].astype(str).str.strip().str.lower().replace('nan', ''))

Display Cleaned Data:

In [18]:
display(df.head())

,timestamp,course,motivation_required_course,motivation_keep_current,motivation_career_advancement,motivation_career_change,motivation_prof_dev,motivation_job_displacement,motivation_relocation,motivation_it_certifications,...,interest_cybersecurity,interest_app_development,interest_data_analytics,interest_ml_ai,interest_programming,interest_game_design,interest_hardware_repair,gender,race,age
0,2024/09/10 10:47:35 AM AST,cmp 126 computer technology and applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,prefer not to say,hispanic or latino;black/african american;whit...,19-20
1,2024/09/10 11:00:05 AM AST,cmp 126 computer technology and applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,woman,hispanic or latino,19-20
2,2024/09/10 11:02:51 AM AST,cmp 126 computer technology and applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,man,choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,cmp 126 computer technology and applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,man,hispanic or latino,19-20
4,2024/09/10 8:37:36 PM AST,cmp 101 computer information literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,woman,white/caucasian,19-20

In [19]:
df.to_csv("nonmajors_survey_cleaned_survey_data.csv", index=False)

### Citations:

chatgpt.com